marketplace/conversation/urls.py
from django.urls import path, include
from . import views
# from core.views import contact

app_name = 'conversation'

urlpatterns = [
    path('new/<int:item_pk>/', views.new_conversation, name="new"),
    path('inbox/',views.inbox, name="inbox"),
    path('<int:pk>/', views.detail, name="detail"),

]

marketplace/core/urls.py
from . import views
from django.urls import path
from django.contrib.auth import views as auth_views
from .forms import LoginForm
from django.contrib.auth.views import LogoutView

app_name = 'core'
urlpatterns = [
    path('', views.index, name="home"),
    path('contact/', views.contact, name="contact"),
    path('signup/', views.signup, name="signup"),
    path('login/', auth_views.LoginView.as_view(template_name='core/login.html', authentication_form=LoginForm), name="login"),
    path('logout/', LogoutView.as_view(), name='logout'),


]

marketplace/dashboard/urls.py
from django.urls import path, include
from . import views

app_name = 'dashboard'

urlpatterns = [
    path('', views.index, name='index'),
]

marketplace/items/urls.py
from django.urls import path
from . import views


app_name = 'item'

urlpatterns = [
    path('', views.items, name="items"),
    path('new/', views.new, name="new"),
    path('<int:pk>/', views.detail, name="detail"),
    path('<int:pk>/edit/', views.edit, name="edit"),
    path('<int:pk>/delete/', views.delete, name="delete"),
]

marketplace/marketplace/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
# from core.views import contact

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("core.urls")),
    path('items/', include("items.urls")),
    path('dashboard/',include("dashboard.urls")),
    path('inbox/', include("conversation.urls")),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

marketplace/core/models.py
from django.db import models

# Create your models here.

marketplace/core/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User



class LoginForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Your username',
        'class' : 'w-full py-4 px-6 rounded-xl'
    }))

    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'password',
        'class' : 'w-full py-4 px-6 rounded-xl'
    }))

class SignupForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username', 'email', 'password1','password2')

    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Your username',
        'class' : 'w-full py-4 px-6 rounded-xl'
    }))

    email = forms.CharField(widget=forms.EmailInput(attrs={
        'placeholder': 'email',
        'class' : 'w-full py-4 px-6 rounded-xl'
    }))

    password1 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'password',
        'class' : 'w-full py-4 px-6 rounded-xl'
    }))

    password2 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'confirm password',
        'class' : 'w-full py-4 px-6 rounded-xl'
    }))

marketplace/core/views.py
from django.shortcuts import render, redirect
from items.models import Category, Item
from .forms import SignupForm




# Create your views here.
def index(request):
    items = Item.objects.filter(is_sold=False)[0:]
    categories = Category.objects.all()

    return render(request,"core/index.html",{
        'categories': categories,
        'items': items,
    })

def contact(request):
    return render(request, "core/contact.html")

def logout(request):
    return redirect()


def signup(request):
    if request.method == 'POST':
        form = SignupForm(request.POST)
        if form.is_valid():
            form.save()

            return redirect('/login/')
    else:
        form = SignupForm()

    return render(request, "core/signup.html", {
        'form': form,
    })

marketplace/core/templates/core/about.html
{% extends "core/base.html" %}

{% block title %}About{% endblock title %}
{% block content %}
<h1>ye this is about page</h1>
    {% endblock content %}

marketplace/core/templates/core/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- <link rel="stylesheet" href=""> -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <script src="https://cdn.tailwindcss.com"></script>
    <title>{% block title %}{% endblock title %}</title>
</head>
<body>
    <nav class="py-6 px-6 flex justify-between items-center border-b border-gray-200">
        <a href="/" class="text-xl font-semibold" style="font-family: 'Open Sans', sans-serif;">OnMark</a>
        <div class="space-x-6">
            <a href="{% url "item:new" %}" class="px-5 py-3 text-lg font-semibold bg-blue-500 text-white rounded-xl hover:bg-blue-700"><i class="fa fa-plus"></i>
                Add Item</a>
            <a href="{% url "item:items" %}" class="px-5 py-3 text-lg font-semibold bg-gray-500 text-white rounded-xl hover:bg-gray-700"><i class="fa fa-search"></i> </a>
            {% if request.user.is_authenticated %}
            <a href="{% url "conversation:inbox" %}" class="px-6 py-3 text-lg font-semibold bg-orange-500 text-white rounded-xl hover:bg-orange-700">Inbox</a>
            <a href="{% url "dashboard:index" %}" class="px-6 py-3 text-lg font-semibold bg-teal-500 text-white rounded-xl hover:bg-teal-700">Dashboard</a>
            <form action="{% url 'core:logout' %}" method="post" class="inline">
                {% csrf_token %}
                <button type="submit" class="px-4 py-1 text-lg font-semibold bg-red-500 text-white rounded-xl hover:bg-red-700"><i class="fa fa-power-off"></i></button>
            </form>
            {% else %}
                <a href="{% url "core:signup" %}" class="px-6 py-3 text-lg font-semibold bg-teal-500 text-white rounded-xl hover:bg-teal-700">Sign up</a>
                <a href="{% url "core:login" %}" class="px-6 py-3 text-lg font-semibold bg-gray-500 text-white rounded-xl hover:bg-gray-700">Log in</a>
        {% endif %}
        </div>
    </nav>

    <div class="px-6 py-6">
        {% block content %}{% endblock content %}
    </div>

    <footer class="py-6 px-6 flex justify-between bg-gray-800">
        <div class="w-2/3 pr-10">
            <h3 class="mb-5 font-semibold text-gray-400">About</h3>
            <p class="text-lg text-gray-500">Lorem ipsum dolor sit amet consectetur adipisicing elit. Quo molestias ut voluptas nobis laboriosam accusamus recusandae odit. Quis perferendis excepturi ducimus.</p>
        </div>

        <div class="w-1/3">
            <h3 class="mb-5 font-semibold text-gray-400">Menu</h3>

            <ul class="space-y-2">
                <li><a href="/" class="text-lg text-teal-500 hover:text-teal-700">About</a></li>
                <li><a href="{% url "core:contact" %}" class="text-lg text-teal-500 hover:text-teal-700">Contact</a></li>
                <li><a href="#" class="text-lg text-teal-500 hover:text-teal-700">Privacy Policy</a></li>
                <li><a href="#" class="text-lg text-teal-500 hover:text-teal-700">Terms and Conditions</a></li>
            </ul>
        </div>
    </footer>
</body>
</html>

marketplace/core/templates/core/contact.html
{% extends "core/base.html" %}

{% block title %}Contact{% endblock title %}
{% block content %}
<h1>This is contact page</h1>
    {% endblock content %}

marketplace/core/templates/core/index.html
{% extends "core/base.html" %}

{% block title %}Home{% endblock title %}
{% block content %}
<style>
    .item-container {
        display: block;
        text-decoration: none;
    }

    .image-container {
        position: relative;
        height: 200px; /* Set a fixed height for the image container */
        overflow: hidden; /* Hide any overflow to keep it within the container */
    }

    .item-image {
        width: 100%;
        height: 100%;
        object-fit: cover; /* Maintain aspect ratio and cover the container */
    }
    .item-card{
        transition: transform 0.3s ease-in-out; /* Add a smooth transition effect */

    }
    .item-card:hover {
        transform: scale(0.8);
    }
</style>
<div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
    <h2 class="mb-12 text-2xl text-center">Newest items</h2>

    <div class="grid grid-cols-3 gap-3">
        {% for item in items %}
        <div class="item-card">
            <a href="{% url "item:detail" item.id %}" class="item-container">
                <div class="image-container">
                    <img src="{{ item.image.url }}" class="rounded-t-xl item-image">
                </div>

                <div class="p-6 bg-white rounded-b-xl">
                    <h2 class="text-2xl">{{item.name}}</h2>
                    <p class="text-gray-500">Price: ${{item.price}}</p>
                </div>
            </a>
        </div>
        {% endfor %}
    </div>
</div>

<div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
    <h2 class="mb-12 text-2xl text-center">Categories</h2>

    <div class="grid grid-cols-3 gap-3">
        {% for category in categories %}
        <div>
            <a href="#">
                <div class="p-6 bg-white rounded-b-xl">
                    <h2 class="text-2xl">{{category.name}}</h2>
                    <p class="text-gray-500">{{category.items.count}} items</p>
                </div>
            </a>
        </div>
        {% endfor %}
    </div>
{% endblock content %}

marketplace/core/templates/core/login.html
{% extends "core/base.html" %}

{% block title %}Login{% endblock title %}

{% block content %}
<div class="w-1/2 my-6 mx-auto p-6 bg-gray-100 rounded-xl">
    <h1 class="mb-6 text-3xl"> Log in</h1>

    <form method='post' action=".">
        {% csrf_token %}

        {{ form.non_fiels_errors }}

        <div class="mb-3">
            <label class="inline-block mb-2">Username</label><br>
            {{ form.username }}
        </div>

        

        <div class="mb-3">
            <label class="inline-block mb-2">Password</label><br>
            {{ form.password }}
        </div>

        

        {% if form.errors or form.non_field_errors %}
        <div class="mb-3 p-6 bg-red-100 rounded-xl">
            {% for field in form %}
            {{ field.errors }}
            {% endfor %}

            {{ form.non_field_errors }}
        </div>
        {% endif %}



        <button class="py-4 px-8 text-lg bg-teal-500 hover:bg-teal-700 rounded-xl text-white">Submit</button>
    </form>
</div>
{% endblock content %}

marketplace/core/templates/core/signup.html
{% extends "core/base.html" %}

{% block title %}Signup{% endblock title %}

{% block content %}
<div class="w-1/2 my-6 mx-auto p-6 bg-gray-100 rounded-xl">
    <h1 class="mb-6 text-3xl"> Sign up</h1>

    <form method='post' action=".">
        {% csrf_token %}

        {{ form.non_fiels_errors }}

        <div class="mb-3">
            <label class="inline-block mb-2">Username</label><br>
            {{ form.username }}
        </div>

        <div class="mb-3">
            <label class="inline-block mb-2">Email</label><br>
            {{ form.email }}
        </div>

        <div class="mb-3">
            <label class="inline-block mb-2">Password</label><br>
            {{ form.password1 }}
        </div>

        <div class="mb-3">
            <label class="inline-block mb-2">Confirm Password</label><br>
            {{ form.password2 }}
        </div>

        {% if form.errors or form.non_field_errors %}
        <div class="mb-3 p-6 bg-red-100 rounded-xl">
            {% for field in form %}
            {{ field.errors }}
            {% endfor %}

            {{ form.non_field_errors }}
        </div>
        {% endif %}



        <button class="py-4 px-8 text-lg bg-teal-500 hover:bg-teal-700 rounded-xl text-white">Submit</button>
    </form>
</div>
{% endblock content %}